AspidaTest/AspidaTest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app1.urls"))
]

AspidaTest/app1/urls.py
from re import template
from xml.dom.minidom import Document
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = "app1"
urlpatterns = [
    path("users", views.users, name="users"),
    path("register", views.register, name="register"),
    path("", LoginView.as_view(template_name='app1/login.html'), name="login"),
    path("logout", LogoutView.as_view(template_name='app1/index.html'), name="logout"),
    path("modelbd", views.modelbd, name="modelbd"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AspidaTest/app1/models.py
from django.db import models
from django.contrib.auth.models import User

class Brands(models.Model):
    name = models.CharField(max_length=80)  #tipo de datos de modelos en este caso "Varchar"

    def __str__(self):
        return self.name

class Users(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    brand_id = models.ForeignKey(Brands, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

AspidaTest/app1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class formRegister(UserCreationForm):

	username = forms.CharField(label='identificación')
	password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Confirma Contraseña', widget=forms.PasswordInput)
	first_name = forms.CharField(label='Nombres')
	last_name = forms.CharField(label='Apellidos')

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username','password1', 'password2']
		help_texts = {k:"" for k in fields }

AspidaTest/app1/views.py
from contextlib import redirect_stderr
from django.shortcuts import render, get_object_or_404, redirect
from .models import Users, Brands
from django.contrib.auth.models import User
from .forms import formRegister

def index(request):
    return render(request, "app1/index.html")

def register(request):
    list_brands = Brands.objects.all()
    if request.method == 'POST':
        form = formRegister(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST["username"]
            select = request.POST["select"]
            brand= get_object_or_404(Brands, pk=select)
            user= get_object_or_404(User, username=username)
            app1_user = Users(user=user,brand_id=brand)
            app1_user.save()
            return redirect('app1:login')
            #return render(request, "app1/login.html")
    else:
        form = formRegister()

    context = {'form' : form,
               "list_brands": list_brands}
    return render(request, 'app1/register.html', context)

def users(request):
    list_users = Users.objects.all()
    return render(request, "app1/users.html", {
        "list_users": list_users
    })

def modelbd(request):
    return render(request, "app1/modelbd.html")

AspidaTest/app1/templates/app1/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Logout</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'register.css' %}">
  </head>
  <body class="bg-dark">
    <div class="row justify-content-center align-items-center vh-100 m-0">
        <div class="col-sm-4 bg-light border border-primary rounded button-logout">
          <div class="row">
            <div class="col">
              <p>has salido de la aplicación</p>
            </div>
            <div class="col">
              <div class="float-end">
                  <a href="https://github.com/Bfiq/TestTecnicoAspida/tree/main/AspidaTest">
                      <i class="bi bi-github">
                          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                              <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                          </svg>
                      </i>
                  </a>
              </div>
            </div>  
            <br/>    
          </div> 
          <div class="row m-0">
            <a class="btn btn-danger btn-block" href="{% url 'app1:login' %}">Volver al login</a>       
          </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

AspidaTest/app1/templates/app1/login.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'register.css' %}">
  </head>
  <body class="bg-dark">
    </div>
    {% if error_message %}
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div>
                llena todos los campos!
            </div>
        </div>
    {% endif %}
    <div class="row justify-content-center align-items-center vh-100 m-0">
        <div class="col-sm-4 bg-light border border-primary rounded">
            <div class="float-end top-icon">
                <a href="{% url 'app1:modelbd' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-filetype-sql" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M14 4.5V14a2 2 0 0 1-2 2v-1a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5L14 4.5ZM0 14.841a1.129 1.129 0 0 0 .401.823c.13.108.288.192.478.252s.411.091.665.091c.338 0 .624-.053.858-.158.237-.106.416-.252.54-.44a1.17 1.17 0 0 0 .187-.656c0-.224-.045-.41-.135-.56a1 1 0 0 0-.375-.357 2.027 2.027 0 0 0-.565-.21l-.621-.144a.97.97 0 0 1-.405-.176.369.369 0 0 1-.143-.299c0-.156.061-.284.184-.384.125-.101.296-.152.513-.152.143 0 .266.022.37.068a.624.624 0 0 1 .245.181.56.56 0 0 1 .12.258h.75a1.092 1.092 0 0 0-.199-.566 1.21 1.21 0 0 0-.5-.41 1.813 1.813 0 0 0-.78-.152c-.293 0-.552.05-.776.15-.225.099-.4.24-.528.421-.127.182-.19.395-.19.639 0 .201.04.376.123.524.082.149.199.27.351.367.153.095.332.167.54.213l.618.144c.207.049.36.113.462.193a.387.387 0 0 1 .153.325c0 .11-.029.207-.085.29A.558.558 0 0 1 2 15.31c-.111.047-.249.07-.413.07-.117 0-.224-.013-.32-.04a.835.835 0 0 1-.248-.115.579.579 0 0 1-.255-.384H0Zm6.878 1.489-.507-.739c.176-.162.31-.362.401-.6.092-.239.138-.507.138-.806v-.501c0-.371-.07-.693-.208-.967a1.495 1.495 0 0 0-.589-.636c-.256-.15-.561-.225-.917-.225-.351 0-.656.075-.914.225-.256.149-.453.36-.592.636a2.138 2.138 0 0 0-.205.967v.5c0 .37.069.691.205.965.139.273.336.485.592.636a1.8 1.8 0 0 0 .914.222 1.8 1.8 0 0 0 .6-.1l.294.422h.788ZM4.262 14.2v-.522c0-.246.038-.456.114-.63a.91.91 0 0 1 .325-.398.885.885 0 0 1 .495-.138c.192 0 .357.046.495.138a.88.88 0 0 1 .325.398c.077.174.115.384.115.63v.522c0 .164-.018.312-.053.445-.035.13-.087.244-.155.34l-.106-.14-.105-.147h-.733l.451.65a.638.638 0 0 1-.251.047.872.872 0 0 1-.487-.147.916.916 0 0 1-.32-.404 1.67 1.67 0 0 1-.11-.644Zm3.986 1.057h1.696v.674H7.457v-3.999h.79v3.325Z"/>
                    </svg>
                </a>
                <a href="https://github.com/Bfiq/TestTecnicoAspida">
                    <i class="bi bi-github">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                        </svg>
                    </i>
                </a>
            </div>
            <br/>
            <div class="title">
                <center>
                    <h5 class="card-header ">
                        Ingreso
                    </h5>
                </center>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary form-control btn-block">Ingresar</button>
                    <a class="btn btn-primary orm-control btn-block" href="{% url 'app1:register' %}">Registrar</a>
                </div>
            </form>
            <br/>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

AspidaTest/app1/templates/app1/modelbd.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'register.css' %}">
  </head>
  <body class="bg-dark">
    {% if error_message %}
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div>
                llena todos los campos!
            </div>
        </div>
    {% endif %}
    <div class="row justify-content-center align-items-center vh-100 m-0">
        <div class="col-sm-6 bg-white border border-primary rounded">
            <div class="title">
                <center>
                    <h5 class="card-header ">
                        Modelo de la Base de Datos
                    </h5>
                </center>
            </div>
            <img src="../../static/images/modeldb-test-aspida.png"/>
            <br/>
            <div class="pab-bot">
                <center>
                    <a class="btn btn-danger btn-center" href="{% url 'app1:login' %}">Volver al login</a>       
                </center>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

AspidaTest/app1/templates/app1/register.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body class="bg-dark">
    {% if error_message %}
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div>
                llena todos los campos!
            </div>
        </div>
    {% endif %}
    <div class="row justify-content-center align-items-center vh-100 m-0">
        <div class="col-sm-4 bg-light border border-primary rounded">
            <br/>
            <center>
            <h5 class="card-header ">
                Registro
            </h5>
        </center>
            <br/>
            <form action="{% url 'app1:registerFormUser'%}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Nombres</label>
                    <input type="text" class="form-control" name="names" required>
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Apellidos</label>
                    <input type="text" class="form-control" name="lastname" required>
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Identificación</label>
                    <input type="text" class="form-control" name="id" required>
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">contraseña</label>
                    <input type="password" class="form-control" name="password" required>
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Marca</label>
                    {% if list_brands %}
                        <select class="form-select" name="select" aria-label="Default select example">
                            <option selected>Escoge una opción</option>
                            {% for brand in list_brands %}
                                <option value={{brand.id}}>{{brand.name}}</option>
                            {% endfor %}
                        </select>
                    {% else %}
                        <p>Error</p>
                    {% endif %}
                </div>
                <input type="submit" class="btn btn-primary form-control btn-block" value="Registrar"/>
                <br/>
            </form>
            <br/>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

AspidaTest/app1/templates/app1/users.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Users</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'register.css' %}">
    </head>
    <body class="bg-dark">
    {% if request.user.is_authenticated %}
        <div class="row justify-content-center align-items-center vh-100">
            <div class="col-9 bg-light border border-primary rounded">
                {% if list_users %}
                    <div class="row top-user">
                        <div class="col users"><p class="user bg-dark">Usuarios</p></div>
                        <div class="col"><a class="btn btn-danger float-end btn-block" href="{% url 'app1:logout' %}">Salir</a></div>
                    </div>
                    <div class="table-responsive">
                        <table class="table">
                            <thead class="table-dark">
                                <tr>
                                    <td>Nombres</td>
                                    <td>Apellidos</td>
                                    <td>identificación</td>
                                    <td>Marca de portatil</td>
                                    <td>fecha de Registro</td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for user in list_users %}
                                    <tr>
                                        <td>{{user.user.first_name}}</td>
                                        <td>{{user.user.last_name}}</td>
                                        <td>{{user.user.username}}</td>
                                        <td>{{user.brand_id}}</td>
                                        <td>{{user.created_at}}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% endif %}
            </div>
        </div>  
    {% else %}
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-3 bg-light border border-primary rounded">
            <p>Logueate antes de interactuar en la pagina :D</p>
            <center>
                <a class="btn btn-danger btn-block" href="{% url 'app1:login' %}">Volver</a>
            </center>
        </div>
    </div>
    {% endif %}
        
    </body>
</html>